# [info]
site_name: entrycoder的软件开发记事本 #网站大标题
site_author: entrycoder
site_description: entrycoder的软件开发记事本

theme:
  name: material #设置使用material模板
  palette:
    scheme: default #设置为亮色主题
    primary: indigo #设置标题及标签栏颜色为靛蓝
    accent: deep orange #设置可交互组件为暗橙色
  font:
    text: Roboto #设置常规字体
    code: Roboto Mono #设置等宽字体
  language: zh #设置语言为简体中文
  direction: ltr #设置左对齐
  features:
    - navigation.instant #即时加载
    - navigation.tracking #锚点跟踪(url中使用#号确定当前部分处在整体的什么部分)
    - navigation.tabs #导航选项卡
    - navigation.tabs.sticky #粘性导航标签(需启动导航选项卡)
    - navigation.sections #左侧导航显示
    - navigation.expand #默认打开左侧导航，显示所有内容
    - navigation.indexes #部分索引页(将文档附加到章节)
    - navigation.top #返回顶部功能按钮

    - search.suggest #开启搜索建议
    - search.highlight #搜索部分突出显示
    - search.share #搜索共享

    - header.autohide #头部自动隐藏

plugins:
  - search: #开启搜索插件
      lang:
        - en
        - jp
    # separator: '[\s\-\.]' #设置搜索的分词方式
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

extra:
  version:
    provider: mike #版本控制(文档存档)

markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols

# [nav]
nav:
  - 系统环境:
    - Environment/index.md
    - 前端:
        - 在Kylin上安装VUE-CLI等: Environment/front_end/vue_on_kylin.md
  # - 前端开发:

  # - 后端开发:

  - 数据库:
    - Database/index.md
    - RDBMS:
      - MySQL: 
        - MySQ教程 尚硅谷: 
          - 作者的话: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/作者的话.md
          - 修改记录: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/修改记录.md
          - 目录: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/目录.md
          - 文档-基础篇:
            - 第00章_写在前面: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第00章_写在前面.md
            - 第01章_数据库概述: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第01章_数据库概述.md
            - 第02章_MySQL环境搭建: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第02章_MySQL环境搭建.md
            - 第03章_基本的SELECT语句: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第03章_基本的SELECT语句.md
            - 第04章_运算符: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第04章_运算符.md
            - 第05章_排序与分页: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第05章_排序与分页.md
            - 第06章_多表查询: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第06章_多表查询.md
            - 第07章_单行函数: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第07章_单行函数.md
            - 第08章_聚合函数: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第08章_聚合函数.md
            - 第09章_子查询: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第09章_子查询.md
            - 第10章_创建和管理表: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第10章_创建和管理表.md
            - 第11章_数据处理之增删改: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第11章_数据处理之增删改.md
            - 第12章_MySQL数据类型精讲: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第12章_MySQL数据类型精讲.md
            - 第13章_约束: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第13章_约束.md
            - 第14章_视图: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第14章_视图.md
            - 第15章_存储过程与函数: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第15章_存储过程与函数.md
            - 第16章_变量、流程控制与游标: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第16章_变量、流程控制与游标.md
            - 第17章_触发器: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第17章_触发器.md
            - 第18章_MySQL8其它新特性: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第18章_MySQL8其它新特性.md
            - 第19章_写在最后: Database/MySQL/mysql_tutorial__atguigu_BV1iq4y1u7vj/md-docs/第19章_写在最后.md
  - 关于:
    - index.md